<?php

defined('_JEXEC') or die();
 
class JCKFull extends JCKToolbar {
	var $Source = '1';
	var $Save = '';
	var $Cut = '2';
	var $Copy = '';
	var $Paste = '';
	var $PasteText = '';
	var $PasteFromWord = '';
	var $SelectAll = '';
	var $sep_1 = '';
	var $Print = '';
	var $SpellChecker = '';
	var $Scayt = '';
	var $Undo = '3';
	var $Redo = '';
	var $RemoveFormat = '';
	var $sep_2 = '';
	var $Find = '';
	var $Replace = '';
	var $sep_3 = '';
	var $Bold = '4';
	var $Italic = '';
	var $Underline = '';
	var $Strike = '';
	var $sep_4 = '';
	var $Subscript = '';
	var $Superscript = '';
	var $Blockquote = '';
	var $SpecialChar = '';
	var $Form = '5';
	var $Checkbox = '';
	var $Radio = '';
	var $TextField = '';
	var $Textarea = '';
	var $Select = '';
	var $Button = '';
	var $ImageButton = '';
	var $HiddenField = '';
	var $NumberedList = '6';
	var $BulletedList = '';
	var $sep_5 = '';
	var $Outdent = '';
	var $Indent = '';
	var $JustifyLeft = '7';
	var $JustifyCenter = '';
	var $JustifyRight = '';
	var $JustifyBlock = '';
	var $JLink = '8';
	var $Link = '';
	var $Unlink = '';
	var $Anchor = '';
	var $Image = '9';
	var $Flash = '';
	var $Templates = '';
	var $Table = '';
	var $HorizontalRule = '';
	var $Smiley = '';
	var $Styles = '10';
	var $Format = '';
	var $CreateDiv = '';
	var $ShowBlocks = '';
	var $Font = '11';
	var $FontSize = '';
	var $TextColor = '';
	var $BGColor = '';
	var $Maximize = '12';
	var $Preview = '';
	var $sep_6 = '';
	var $About = '';
	var $MediaEmbed = '';
	var $Atdckeditor = '';
	var $SpellCheck = '';
}
?>